<?php
session_start();
if(!isset($_SESSION["user_type"])){
  header("Location:index.php");
}
if(isset($_SESSION["shift_report_printed"])){
    session_destroy();
    header("Location:index.php");
}
else{
  header("location:print-shift-reports.php");
}
?>